apiVersion: v1
kind: ConfigMap
metadata:
  name: app
# ConfigMap: used to store configuration data in key-value pairs
# NOTE: does not support sensitive data. Use secrets for that.
data:
  DEPLOYMENT: {{ .Values.deployment }}
  LOG_LEVEL: {{ .Values.app.logging.level }}
