name: 'Helm Lint'
description: 'Lint Helm charts'

inputs:
  chart-path:
    description: 'Path to the Helm chart directory'
    required: true
    default: 'chart/'

runs:
  using: 'composite'  # Composite: reusable action made up of multiple steps
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      
    - name: Lint Helm charts
      run: |
        helm lint ${{ inputs.chart-path }}
      shell: bash

