apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  # echo 'string' | base64
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzL2Zvbw==
