name: CI
description: Default workflow for the project

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Poetry
        uses: ./.github/actions/poetry-setup
        with:
          poetry-path: 'src/'
          python-version: '3.11'
          poetry-version: '2.1.0'

